version: '3.8'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-service-img
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:13.7-alpine
    container_name: statsdb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./ewm-service
    image: ewm-service-img
    container_name: emw-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewmdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

